name: Release Helm Charts

on:
  push:
    branches: [main]

permissions:
  contents: write  
  pull-requests: write   

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GHUB_GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Print release outputs for debugging
        run: |
          echo "backend--release_created: ${{ steps.release.outputs.backend--release_created }}"
          echo "backend--tag_name:        ${{ steps.release.outputs.backend--tag_name }}"
          echo "frontend--release_created: ${{ steps.release.outputs.frontend--release_created }}"
          echo "frontend--tag_name:        ${{ steps.release.outputs.frontend--tag_name }}"