name: Release Helm Charts

on:
  push:
    branches: [main]

permissions:
  contents: write  
  pull-requests: write   

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GHUB_GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Print release ouput for debugging
        run: |
          echo "Release outputs:"
          echo "Release version: ${{ steps.release.outputs.version }}"
          echo "General output: ${{ steps.release.outputs }}"